### ISSUE TITLE
Incorrect addressing for low memory devices

### ISSUE THREAD

**Issue by geomatsi** [eldruin/eeprom24x-rs#6]
IIUC, current implementation assumes that memory address consists of two bytes. In other words, three consequent address bytes should be sent for each operation: DEV_ADDR, MEM_ADDR_HI, MEM_ADDR_LOW.

However it looks like this is the case only for at24c32 and higher. For at24c16 and lower devices high memory address is passed as a part of DEV_ADDR.

**Comment by eldruin** [comment]
I see. That is actually the case according to the [datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/20005858A.pdf). Good catch!
I will have a look at the addressing model in at24c16 and lower devices and release a fix soon. Thanks!

**Comment by eldruin** [comment]
This has been fixed in https://github.com/eldruin/eeprom24x-rs/releases/tag/v0.3.0
